# Generated by Django 3.0.3 on 2020-03-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200331_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
