# Generated by Django 3.0.3 on 2020-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
