# Generated by Django 3.0.3 on 2020-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcart',
            name='date',
            field=models.DateTimeField(blank=True, default='2000-10-10 10:10'),
            preserve_default=False,
        ),
    ]
