# Generated by Django 3.0.3 on 2020-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_reservationcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
