# Generated by Django 3.0.3 on 2020-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200513_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
