# Generated by Django 3.0.3 on 2020-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20200513_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total',
            new_name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrive',
            field=models.CharField(blank=True, choices=[('Havalimani', 'Havalimani'), ('Havalimani-*', 'Havalimani-*'), ('Sehir-A', 'Sehir-A'), ('Sehir-B', 'Sehir-B'), ('Sehir-C', 'Sehir-C'), ('-', '-')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='take_off',
            field=models.CharField(blank=True, choices=[('Havalimani', 'Havalimani'), ('Havalimani-*', 'Havalimani-*'), ('Sehir-A', 'Sehir-A'), ('Sehir-B', 'Sehir-B'), ('Sehir-C', 'Sehir-C'), ('-', '-')], default='-', max_length=20),
        ),
    ]
