# Generated by Django 3.0.3 on 2020-05-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200513_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationCart',
        ),
    ]
