# Generated by Django 3.0.3 on 2020-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_delete_reservationcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='TransferCar',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
