# Generated by Django 3.0.3 on 2020-05-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_transfercar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='TransferCar',
        ),
    ]
